package com.inventra.backend.service;
import com.inventra.backend.dto.*; import com.inventra.backend.exception.InsufficientStockException; import com.inventra.backend.model.*; import com.inventra.backend.repository.*; import org.springframework.stereotype.Service; import java.time.LocalDateTime;
@Service public class InventoryCoreService { private final InventoryRepository ir; private final ProductRepository pr; private final WarehouseRepository wr; private final StockMovementRepository mr; public InventoryCoreService(InventoryRepository i,ProductRepository p,WarehouseRepository w,StockMovementRepository m){ir=i;pr=p;wr=w;mr=m;}
public java.util.List<InventoryResponse> allForWarehouse(String wid){wr.findById(wid).orElseThrow(()->new IllegalArgumentException("Warehouse not found"));return ir.findByWarehouseId(wid).stream().map(this::map).toList();}
public Inventory get(String wid,String pid){wr.findById(wid).orElseThrow(()->new IllegalArgumentException("Warehouse not found"));pr.findById(pid).orElseThrow(()->new IllegalArgumentException("Product not found"));return ir.findByWarehouseIdAndProductId(wid,pid).orElseGet(()->{Inventory x=new Inventory();x.setWarehouseId(wid);x.setProductId(pid);return x;});}
public InventoryResponse adjust(String wid,InventoryAdjustmentRequest r){Inventory x=get(wid,r.productId());int next=x.getQuantity()+r.quantity();if(next<0||next<x.getReservedQuantity())throw new IllegalStateException("Inventory cannot become negative or below reserved stock");x.setQuantity(next);x.setUpdatedAt(LocalDateTime.now());ir.save(x);syncProduct(r.productId());movement(r.productId(),wid,StockMovementType.ADJUSTMENT,r.quantity(),x.getQuantity(),null,r.reason());return map(x);}
public InventoryResponse receive(String wid,String pid,int q,String ref,String reason){Inventory x=get(wid,pid);x.setQuantity(x.getQuantity()+q);x.setUpdatedAt(LocalDateTime.now());ir.save(x);syncProduct(pid);movement(pid,wid,StockMovementType.PURCHASE,q,x.getQuantity(),ref,reason);return map(x);}
public InventoryResponse reserve(String wid,String pid,int q,String ref){Inventory x=get(wid,pid);if(x.getAvailableQuantity()<q)throw new InsufficientStockException("Insufficient available stock for product "+pid);x.setReservedQuantity(x.getReservedQuantity()+q);x.setUpdatedAt(LocalDateTime.now());ir.save(x);movement(pid,wid,StockMovementType.RESERVATION,q,x.getAvailableQuantity(),ref,"Order reservation");return map(x);}
public InventoryResponse release(String wid,String pid,int q,String ref){Inventory x=get(wid,pid);x.setReservedQuantity(Math.max(0,x.getReservedQuantity()-q));x.setUpdatedAt(LocalDateTime.now());ir.save(x);movement(pid,wid,StockMovementType.RELEASE,q,x.getAvailableQuantity(),ref,"Reservation released");return map(x);}
public InventoryResponse fulfill(String wid,String pid,int q,String ref){Inventory x=get(wid,pid);if(x.getReservedQuantity()<q||x.getQuantity()<q)throw new InsufficientStockException("Reserved/physical stock is insufficient");x.setReservedQuantity(x.getReservedQuantity()-q);x.setQuantity(x.getQuantity()-q);x.setUpdatedAt(LocalDateTime.now());ir.save(x);syncProduct(pid);movement(pid,wid,StockMovementType.SALE,q,x.getQuantity(),ref,"Order fulfilled");return map(x);}
public InventoryResponse returnStock(String wid,String pid,int q,String ref){return receive(wid,pid,q,ref,"Customer return");}
public void transfer(String from,String to,String pid,int q,String reason){if(from.equals(to))throw new IllegalArgumentException("Source and destination warehouses must differ");Inventory src=get(from,pid);if(src.getAvailableQuantity()<q)throw new InsufficientStockException("Insufficient available stock for transfer");src.setQuantity(src.getQuantity()-q);src.setUpdatedAt(LocalDateTime.now());ir.save(src);Inventory dst=get(to,pid);dst.setQuantity(dst.getQuantity()+q);dst.setUpdatedAt(LocalDateTime.now());ir.save(dst);syncProduct(pid);movement(pid,from,StockMovementType.TRANSFER_OUT,q,src.getQuantity(),to,reason);movement(pid,to,StockMovementType.TRANSFER_IN,q,dst.getQuantity(),from,reason);}
private void syncProduct(String pid){Product p=pr.findById(pid).orElseThrow();int total=ir.findByProductId(pid).stream().mapToInt(Inventory::getQuantity).sum();p.setStockQuantity(total);pr.save(p);}private void movement(String pid,String wid,StockMovementType t,int q,int bal,String ref,String reason){StockMovement m=new StockMovement();m.setProductId(pid);m.setWarehouseId(wid);m.setType(t);m.setQuantity(q);m.setBalanceAfter(bal);m.setReferenceId(ref);m.setReason(reason);mr.save(m);}private InventoryResponse map(Inventory x){return new InventoryResponse(x.getId(),x.getWarehouseId(),x.getProductId(),x.getQuantity(),x.getReservedQuantity(),x.getAvailableQuantity());}}
