import React,{useEffect,useState} from 'react';
import {Routes,Route,Navigate,NavLink,useLocation,useNavigate} from 'react-router-dom';
import api,{errMsg} from './services/api';
import Dashboard from './pages/Dashboard'; import Products from './pages/Products'; import Inventory from './pages/Inventory'; import Warehouses from './pages/Warehouses'; import Operations from './pages/Operations'; import AIHub from './pages/AIHub'; import Login from './pages/Login'; import Register from './pages/Register';
const nav=[['/','Dashboard','⌂'],['/products','Products','▦'],['/inventory','Inventory','◫'],['/warehouses','Warehouses','⌗'],['/operations','Operations','↻'],['/ai','AI Intelligence','✦']];
function Protected({children}){return localStorage.getItem('inventra_token')?<>{children}</>:<Navigate to="/login" replace/>}
function Shell({children}){const loc=useLocation(),navg=useNavigate(),[me,setMe]=useState(null),[open,setOpen]=useState(false); useEffect(()=>{let alive=true; api.get('/auth/me').then(r=>{if(alive)setMe(r.data)}).catch(()=>{if(alive){localStorage.removeItem('inventra_token');localStorage.removeItem('inventra_user');navg('/login',{replace:true})}}); return ()=>{alive=false};},[navg]); const signout=async()=>{try{await api.post('/auth/logout')}catch{} localStorage.removeItem('inventra_token');localStorage.removeItem('inventra_user');navg('/login')}; return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark">I</div><div><b>Inventra</b><span>Inventory intelligence</span></div></div><nav>{nav.map(([to,label,icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>isActive?'active':''}><i>{icon}</i>{label}</NavLink>)}</nav><div className="side-note"><span className="pulse"></span><div><b>System online</b><small>Live inventory sync</small></div></div></aside><main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(!open)}>☰</button><div className="crumb">{loc.pathname==='/'?'Overview':loc.pathname.slice(1).replaceAll('-',' ')}</div><div className="top-actions"><div className="user"><div className="avatar">{(me?.name||'U').slice(0,1).toUpperCase()}</div><div className="user-text"><b>{me?.name||JSON.parse(localStorage.getItem('inventra_user')||'{}').name||'User'}</b><span>{me?.email||''}</span></div></div><button className="signout" onClick={signout}>Sign out</button></div></header><section className="content">{children}</section></main></div>}
function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="*" element={<Protected><Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/products" element={<Products/>}/><Route path="/inventory" element={<Inventory/>}/><Route path="/warehouses" element={<Warehouses/>}/><Route path="/operations" element={<Operations/>}/><Route path="/ai" element={<AIHub/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Shell></Protected>}/></Routes>}
export default App;
